/**
 * ===========================================================================
 *  TOURIST VISA PAGE: CLIENT-SUPPLIED COPY
 * ===========================================================================
 *
 * From the client's "tourist-visa content.pdf", reproduced as written. The
 * page at app/(site)/services/global-visa/tourist-visa/ only arranges it.
 *
 * Two editorial changes, both house style rather than wording:
 *   - The region names used an em dash ("Africa — North & East"). The site
 *     writes a spaced hyphen wherever the copy had one, so they do too.
 *   - The "most often" country board is the same list as on the Global visa
 *     hub, so it is imported from ./visa.js rather than repeated here.
 *
 * REGIONS: each country is [iso, name, route]. `route` is exactly the text in
 * the client's table. A trailing "*" is their asterisk: a valid Schengen, UK
 * or US visa can change the requirement. The colour and filter a route gets
 * come from routeKinds() below, which reads the text, so a route edited here
 * re-files itself without a second field to keep in step.
 */

import { HUB } from "./visa";

export const TOURIST = {
  /** Mid-page CTA boxes (not client copy: written for the layout). */
  ctas: {
    situations: {
      title: "Travelling soon?",
      text: "The destination, your dates and who's going is enough to start. We'll confirm the current rule for your passport before you pay any fee.",
      primary: "Get a document list",
    },
    docs: {
      title: "Want the list for your destination?",
      text: "A document list built for that consulate, not copied from a website. Passport details can wait.",
      primary: "Get a document list",
    },
  },
  meta: {
    title: "Tourist Visa Assistance in Kerala - 197 Destinations",
    description:
      "Tourist and visitor visa files for 197 destinations, from Schengen, the UK and the US to e-visa countries. Prepared the way the consulate reads them: complete, in their order. Kottayam, Kerala.",
  },
  hero: {
    eyebrow: "Visa services",
    title: "Tourist visa",
    lead: "Tourist visas are refused far more often for a thin or inconsistent file than for a bad reason to travel. We prepare the application the way the consulate reads it: complete, in their order, with nothing left for them to wonder about.",
    primary: "Get a document list",
  },
  assurances: HUB.assurances,
  situations: {
    title: "What people come to us for",
    lead: "Not a list of countries: these are the situations travellers arrive with. Tell us yours, even if it isn't here.",
    items: [
      {
        tag: "First trip",
        title: "First time abroad",
        text: "No travel history yet, so the bank file and covering letter have to carry more weight.",
      },
      {
        tag: "Europe",
        title: "Schengen on one visa",
        text: "Applied to the country where you spend most nights. Getting that wrong gets a file rejected.",
        flag: "eu",
      },
      {
        tag: "Family",
        title: "Parents visiting children",
        text: "A son or daughter in the UK, Ireland, Canada or the Gulf. Sponsor letters in order.",
      },
      {
        tag: "Urgent",
        tone: "warn",
        title: "Travel dates close",
        text: "Gulf and Southeast Asia e-visas that can move fast, and appointment slots watched daily.",
      },
      {
        tag: "Groups",
        title: "Families travelling together",
        text: "Each person, including children, gets their own complete file.",
      },
      {
        tag: "Refused",
        tone: "warn",
        title: "Reapplying after a refusal",
        text: "We read the refusal letter with you, and fix what can be fixed before reapplying.",
      },
    ],
  },
  banner: {
    strong: "197 destinations, every one named on this page.",
    text: "We confirm the current rule for your passport before you pay any fee.",
  },
  countries: HUB.countries,
  finder: {
    title: "Every destination, by region",
    lead: "The route shown is the usual one for an Indian passport on a tourist trip. Rules change with little notice, so we confirm yours when you apply. An asterisk marks a country where a valid Schengen, UK or US visa can change the requirement.",
    asterisk: "A valid Schengen, UK or US visa can change the requirement.",
    legend: [
      { kind: "schengen", label: "Schengen visa", text: "one visa for the area" },
      { kind: "evisa", label: "eVisa / eTA", text: "applied online before travel" },
      { kind: "voa", label: "VOA", text: "visa on arrival" },
      { kind: "free", label: "Visa-free", text: "no advance visa" },
      { kind: "required", label: "Visa required", text: "embassy application" },
    ],
  },
  regions: [
    {
      key: "schengen",
      name: "Schengen Europe",
      flag: "eu",
      note: "One visa, twenty-nine countries, plus Monaco, San Marino and Vatican City which you enter on the same visa. The application goes to the country you spend the most nights in, which is not always the one you land in. Getting that wrong is one of the commonest reasons a file is rejected before it is even read.",
      countries: [
        ["at", "Austria", "Schengen visa"],
        ["be", "Belgium", "Schengen visa"],
        ["bg", "Bulgaria", "Schengen visa"],
        ["hr", "Croatia", "Schengen visa"],
        ["cz", "Czechia", "Schengen visa"],
        ["dk", "Denmark", "Schengen visa"],
        ["ee", "Estonia", "Schengen visa"],
        ["fi", "Finland", "Schengen visa"],
        ["fr", "France", "Schengen visa"],
        ["de", "Germany", "Schengen visa"],
        ["gr", "Greece", "Schengen visa"],
        ["hu", "Hungary", "Schengen visa"],
        ["is", "Iceland", "Schengen visa"],
        ["it", "Italy", "Schengen visa"],
        ["lv", "Latvia", "Schengen visa"],
        ["li", "Liechtenstein", "Schengen visa"],
        ["lt", "Lithuania", "Schengen visa"],
        ["lu", "Luxembourg", "Schengen visa"],
        ["mt", "Malta", "Schengen visa"],
        ["nl", "Netherlands", "Schengen visa"],
        ["no", "Norway", "Schengen visa"],
        ["pl", "Poland", "Schengen visa"],
        ["pt", "Portugal", "Schengen visa"],
        ["ro", "Romania", "Schengen visa"],
        ["sk", "Slovakia", "Schengen visa"],
        ["si", "Slovenia", "Schengen visa"],
        ["es", "Spain", "Schengen visa"],
        ["se", "Sweden", "Schengen visa"],
        ["ch", "Switzerland", "Schengen visa"],
        ["mc", "Monaco", "Schengen visa"],
        ["sm", "San Marino", "Schengen visa"],
        ["va", "Vatican City", "Schengen visa"],
      ],
    },
    {
      key: "uk-ireland",
      name: "United Kingdom & Ireland",
      note: "Standard visitor visas for holidays and family visits, including parents visiting children who work there. Online application, documents uploaded, biometrics at the visa centre. Ireland is a separate application with its own rules.",
      emphasis: "Joining a spouse who works in the UK or Ireland is not a visitor visa.",
      seeAlso: ["dependant", "settlement"],
      countries: [
        ["gb", "United Kingdom", "Visa required"],
        ["ie", "Ireland", "Visa required"],
      ],
    },
    {
      key: "north-america",
      name: "United States, Canada & Mexico",
      note: "B1/B2 applications with DS-160 preparation, fee payment and interview slot for the US; the visitor visa (TRV) for Canada, with biometrics at the visa centre. We prepare you for the interview; we cannot attend it with you.",
      countries: [
        ["us", "United States", "Visa required"],
        ["ca", "Canada", "Visa required"],
        ["mx", "Mexico", "Visa required*"],
      ],
    },
    {
      key: "gulf",
      name: "Gulf & Middle East",
      note: "Often the fastest category of all, and the one most likely to have changed since you last travelled. We confirm the current rule for your passport before you pay anything.",
      countries: [
        ["ae", "United Arab Emirates", "eVisa / visa required*"],
        ["sa", "Saudi Arabia", "eVisa / VOA"],
        ["qa", "Qatar", "VOA / visa-free conditions"],
        ["om", "Oman", "eVisa / visa-free conditions"],
        ["bh", "Bahrain", "eVisa / VOA"],
        ["kw", "Kuwait", "eVisa / VOA"],
        ["jo", "Jordan", "VOA / eVisa"],
        ["il", "Israel", "eVisa / ETA rules"],
        ["lb", "Lebanon", "VOA / visa conditions"],
        ["ir", "Iran", "VOA / eVisa"],
        ["iq", "Iraq", "eVisa / rules vary by region"],
        ["sy", "Syria", "Visa required"],
        ["ye", "Yemen", "Visa required"],
        ["ps", "Palestine", "Entry rules apply"],
      ],
    },
    {
      key: "south-asia",
      name: "South Asia & Indian Ocean",
      note: "Short-notice destinations for travellers from Kerala. Several are visa-free or visa-on-arrival for Indian passports, which does not mean there is nothing to prepare.",
      countries: [
        ["lk", "Sri Lanka", "ETA"],
        ["mv", "Maldives", "VOA"],
        ["np", "Nepal", "Visa-free"],
        ["bt", "Bhutan", "Entry permit"],
        ["bd", "Bangladesh", "Visa required"],
        ["pk", "Pakistan", "Visa required"],
        ["af", "Afghanistan", "Visa required"],
        ["mu", "Mauritius", "Visa-free / permit"],
        ["sc", "Seychelles", "Travel authorisation"],
      ],
    },
    {
      key: "southeast-asia",
      name: "Southeast Asia",
      note: "Whether the route is an e-visa, a visa on arrival or a full consulate application, and the route changes more often here than anywhere else.",
      countries: [
        ["sg", "Singapore", "Visa required / eVisa"],
        ["my", "Malaysia", "Visa-free conditions / eVisa"],
        ["th", "Thailand", "Visa-free conditions / eVisa"],
        ["vn", "Vietnam", "eVisa"],
        ["id", "Indonesia", "eVisa / VOA"],
        ["ph", "Philippines", "eTA / visa conditions"],
        ["kh", "Cambodia", "VOA / eVisa"],
        ["la", "Laos", "VOA / eVisa"],
        ["mm", "Myanmar", "eVisa"],
        ["bn", "Brunei", "Visa required"],
        ["tl", "Timor-Leste", "VOA"],
      ],
    },
    {
      key: "east-asia",
      name: "East Asia",
      note: "Document-heavy applications where the itinerary and the financial proof have to agree with each other line for line.",
      countries: [
        ["jp", "Japan", "eVisa"],
        ["kr", "South Korea", "Visa required / K-ETA rules"],
        ["cn", "China", "Visa required"],
        ["hk", "Hong Kong", "Pre-arrival registration / visa"],
        ["mo", "Macau", "Visa-free / VOA conditions"],
        ["tw", "Taiwan", "eVisa / travel authorization"],
        ["mn", "Mongolia", "Visa required / eVisa"],
        ["kp", "North Korea", "Visa required"],
      ],
    },
    {
      key: "central-asia",
      name: "Central Asia & the Caucasus",
      note: "Mostly e-visa routes, and among the easier approvals for an Indian passport when the file is complete.",
      countries: [
        ["kz", "Kazakhstan", "Visa required / eVisa"],
        ["uz", "Uzbekistan", "eVisa"],
        ["kg", "Kyrgyzstan", "eVisa"],
        ["tj", "Tajikistan", "eVisa"],
        ["tm", "Turkmenistan", "Visa required"],
        ["az", "Azerbaijan", "eVisa"],
        ["am", "Armenia", "eVisa"],
        ["ge", "Georgia", "eVisa / visa-free conditions"],
      ],
    },
    {
      key: "rest-of-europe",
      name: "Rest of Europe",
      note: "Non-Schengen Europe, where several countries admit holders of a valid Schengen, UK or US visa without a separate application. Worth checking before you pay a second fee.",
      countries: [
        ["al", "Albania", "eVisa"],
        ["ad", "Andorra", "Visa required"],
        ["by", "Belarus", "Visa-free conditions / visa"],
        ["ba", "Bosnia and Herzegovina", "Visa required"],
        ["cy", "Cyprus", "Visa required"],
        ["md", "Moldova", "eVisa"],
        ["me", "Montenegro", "Visa required*"],
        ["mk", "North Macedonia", "Visa required*"],
        ["ru", "Russia", "eVisa"],
        ["rs", "Serbia", "Visa required*"],
        ["tr", "Türkiye", "Visa required*"],
        ["ua", "Ukraine", "Visa required / eVisa"],
      ],
    },
    {
      key: "africa-north-east",
      name: "Africa - North & East",
      note: "Safari and pilgrimage routes, plus the business travel that runs alongside them. Yellow fever certification matters here as much as the visa.",
      countries: [
        ["eg", "Egypt", "eVisa / VOA"],
        ["ma", "Morocco", "Visa required"],
        ["tn", "Tunisia", "Visa required"],
        ["dz", "Algeria", "Visa required"],
        ["ly", "Libya", "Visa required"],
        ["sd", "Sudan", "Visa required"],
        ["ss", "South Sudan", "Visa required"],
        ["et", "Ethiopia", "eVisa / VOA"],
        ["er", "Eritrea", "Visa required"],
        ["dj", "Djibouti", "eVisa"],
        ["so", "Somalia", "eVisa / VOA"],
        ["ke", "Kenya", "eTA"],
        ["tz", "Tanzania", "eVisa / VOA"],
        ["ug", "Uganda", "eVisa"],
        ["rw", "Rwanda", "VOA / eVisa"],
        ["bi", "Burundi", "VOA / eVisa"],
        ["km", "Comoros", "VOA"],
        ["mg", "Madagascar", "VOA / eVisa"],
      ],
    },
    {
      key: "africa-west-central",
      name: "Africa - West & Central",
      note: "Largely e-visa and visa-on-arrival routes, with invitation letters and vaccination records doing more of the work than they do elsewhere.",
      countries: [
        ["ng", "Nigeria", "eVisa"],
        ["gh", "Ghana", "Visa required / eVisa"],
        ["sn", "Senegal", "Visa required / entry conditions"],
        ["ci", "Côte d'Ivoire", "eVisa"],
        ["bj", "Benin", "eVisa"],
        ["bf", "Burkina Faso", "eVisa"],
        ["cv", "Cabo Verde", "Pre-registration / visa"],
        ["cm", "Cameroon", "eVisa"],
        ["cf", "Central African Republic", "Visa required"],
        ["td", "Chad", "Visa required"],
        ["cg", "Congo, Republic", "Visa required"],
        ["cd", "Democratic Republic of the Congo", "Visa required"],
        ["gq", "Equatorial Guinea", "eVisa"],
        ["ga", "Gabon", "eVisa"],
        ["gm", "Gambia", "Visa required"],
        ["gn", "Guinea", "eVisa"],
        ["gw", "Guinea-Bissau", "VOA / eVisa"],
        ["lr", "Liberia", "Visa required / eVisa"],
        ["ml", "Mali", "Visa required"],
        ["mr", "Mauritania", "eVisa"],
        ["ne", "Niger", "Visa required"],
        ["st", "São Tomé and Príncipe", "eVisa"],
        ["sl", "Sierra Leone", "eVisa / VOA"],
        ["tg", "Togo", "VOA / eVisa"],
      ],
    },
    {
      key: "africa-southern",
      name: "Africa - Southern",
      note: "South Africa remains the anchor destination; the neighbours are usually added to the same trip and each needs its own file.",
      countries: [
        ["za", "South Africa", "eVisa"],
        ["na", "Namibia", "eVisa / VOA"],
        ["bw", "Botswana", "eVisa"],
        ["zw", "Zimbabwe", "VOA / eVisa"],
        ["zm", "Zambia", "eVisa / VOA"],
        ["mw", "Malawi", "eVisa / VOA"],
        ["mz", "Mozambique", "eVisa / VOA"],
        ["ao", "Angola", "Visa-free"],
        ["ls", "Lesotho", "eVisa"],
        ["sz", "Eswatini", "eVisa"],
      ],
    },
    {
      key: "oceania",
      name: "Oceania & the Pacific",
      note: "Visitor and family-visit applications lodged online, with health and character requirements checked before submission. Pacific island entry rules are short and strict.",
      countries: [
        ["au", "Australia", "eVisa"],
        ["nz", "New Zealand", "Visa required / NZeTA conditions"],
        ["fj", "Fiji", "Visa-free"],
        ["pg", "Papua New Guinea", "eVisa"],
        ["ws", "Samoa", "Entry permit on arrival"],
        ["to", "Tonga", "VOA / visa required"],
        ["vu", "Vanuatu", "Visa-free"],
        ["sb", "Solomon Islands", "Visa required"],
        ["ki", "Kiribati", "Visa required"],
        ["tv", "Tuvalu", "VOA"],
        ["nr", "Nauru", "Visa required"],
        ["pw", "Palau", "VOA"],
        ["mh", "Marshall Islands", "Visa required / permit"],
        ["fm", "Micronesia", "Visa-free"],
      ],
    },
    {
      key: "americas",
      name: "The Americas - Caribbean & Latin America",
      note: "Long-haul leisure and family visits, and the category where an unnecessary transit visa catches travellers out most often.",
      countries: [
        ["ag", "Antigua and Barbuda", "eVisa"],
        ["bs", "Bahamas", "Visa required"],
        ["bb", "Barbados", "Visa-free"],
        ["bz", "Belize", "Visa required"],
        ["cr", "Costa Rica", "Visa required"],
        ["cu", "Cuba", "Visa required / eVisa"],
        ["dm", "Dominica", "Visa-free"],
        ["do", "Dominican Republic", "eVisa / entry authorization"],
        ["sv", "El Salvador", "Visa required"],
        ["gd", "Grenada", "Visa required / online authorization"],
        ["gt", "Guatemala", "Visa required"],
        ["ht", "Haiti", "Visa-free"],
        ["hn", "Honduras", "Visa required"],
        ["jm", "Jamaica", "Visa-free"],
        ["ni", "Nicaragua", "Visa required"],
        ["pa", "Panama", "Visa required"],
        ["kn", "Saint Kitts and Nevis", "eTA / online authorization"],
        ["lc", "Saint Lucia", "Visa-free / eVisa conditions"],
        ["vc", "Saint Vincent and the Grenadines", "Visa-free"],
        ["tt", "Trinidad and Tobago", "Visa required"],
        ["ar", "Argentina", "eVisa"],
        ["bo", "Bolivia", "VOA / eVisa"],
        ["br", "Brazil", "Visa required"],
        ["cl", "Chile", "Visa required"],
        ["co", "Colombia", "Visa required"],
        ["ec", "Ecuador", "Visa required"],
        ["gy", "Guyana", "Visa required"],
        ["py", "Paraguay", "Visa required"],
        ["pe", "Peru", "Visa required"],
        ["sr", "Suriname", "eVisa / online authorization"],
        ["uy", "Uruguay", "Visa required"],
        ["ve", "Venezuela", "Visa required"],
      ],
    },
  ],
  file: {
    title: "The parts that decide how a file reads",
    documents: {
      title: "Documents we help you prepare",
      items: [
        "Passport checked for validity and blank pages against the country's own rule",
        "Photographs at the exact size and background the consulate specifies",
        "Bank statements and income proof, in the order the file is read",
        "Employment or business letters, and written leave approval",
        "A day-by-day itinerary matched to real flight and hotel bookings",
        "Invitation and sponsor letters where family is hosting you",
        "Travel insurance that meets the country's minimum cover",
        "Previous visas and refusals, declared and explained",
      ],
    },
    before: {
      title: "Before you apply",
      items: [
        ["Start early.", "Appointment availability, not processing time, usually decides when you can travel"],
        ["Don't buy non-refundable flights", "before the visa is granted"],
        ["Names must match the passport exactly,", "on every document and ticket"],
        ["Always declare a previous refusal.", "A hidden one is treated far more seriously than an old one"],
        ["Check passport validity.", "Most countries want it to run well beyond your return date"],
        ["Every traveller needs their own file,", "including children"],
      ],
    },
  },
  process: {
    title: "What actually happens after you message us",
    lead: "No forms to download and no login. You tell a person where you're going, and they do the rest.",
    steps: [
      {
        title: "You send the trip",
        text: "Where, roughly when, who's travelling. WhatsApp, a call or the form. Exact dates can come later.",
      },
      {
        title: "We send the list",
        text: "A document list built for that consulate, not copied from a website.",
      },
      {
        title: "We check the file",
        text: "Forms filled and checked against your passport, line by line.",
      },
      {
        title: "We book and submit",
        text: "The appointment, biometrics and submission, rebooked if an earlier slot opens.",
      },
      {
        title: "Until it's back",
        text: "Tracked until the passport is in your hand. Consulate, centre and our fees listed separately.",
      },
    ],
  },
  why: {
    title: "Why a complete file matters",
    paragraphs: [
      "A consulate officer spends minutes on a file, not hours. If the bank statement doesn't match the itinerary, or the leave letter doesn't match the dates, the easy answer is no, however good your reason for travelling.",
      "We build the file so every document agrees with every other one, and so the officer finds what they're looking for in the order they look for it. And if a visa is refused anyway, we read the letter with you and tell you what can be fixed.",
    ],
  },
  closing: {
    title: "Tell us where you're going. We'll send the document list.",
    text: "The destination, your dates and who's going is enough to start. Passport details can wait.",
    primary: "Get a document list",
  },
};

export { routeKinds } from "./visa-routes";
